ddn/apps/core/urls.py
from django.urls import path
from .views import HomePage, TypesPage, GoodsPage


app_name = 'core'
urlpatterns = [
	path('', HomePage.as_view(), name="home"),
	path('types/<slug:type_slug>/', TypesPage.as_view(), name="types"),
	path(
		'goods/<slug:good_slug>/',
		GoodsPage.as_view(),
		name="goods"),
]

ddn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

ddn/apps/core/models.py
from django.db import models
from django.urls import reverse


class Types(models.Model):
	name = models.CharField(
		verbose_name="Тип товара",
		max_length=255,
		blank=False,
		null=False)
	published = models.DateTimeField(
		auto_now_add=True,
		db_index=True,
		verbose_name='Дата публикации')
	slug = models.SlugField(
		unique=True,
		db_index=True,
		null=True)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('core:types', kwargs={'type_slug': self.slug})

	class Meta:
		verbose_name = "Тип товара"
		verbose_name_plural = "Типы товаров"
		ordering = ['name']


class Goods(models.Model):
	name = models.CharField(
		verbose_name="Название товара",
		max_length=255,
		blank=False,
		null=False)
	description = models.TextField(
		verbose_name="Описание товара",
		blank=False,
		null=False)
	price = models.FloatField(
		verbose_name="Цена товара",
		blank=False,
		null=False)
	type_good = models.ForeignKey(
		Types,
		on_delete=models.PROTECT,
		related_name='+')
	slug = models.SlugField(
		unique=True,
		db_index=True,
		null=True,
		allow_unicode=True)
	pub_date = models.DateTimeField(
		auto_now_add=True,
		db_index=True,
		verbose_name='Дата публикации')
	pub_update = models.DateField(
		auto_now=True,
		verbose_name='Дата обновления публикации')
	published = models.BooleanField(null=True)

	def __str__(self):
		return f"{self.name} with price: {self.price} \
			type: {self.type_good}"

	def get_absolute_url(self):
		return reverse('core:goods', kwargs={'good_slug': self.slug})

	class Meta:
		verbose_name = "Товар"
		verbose_name_plural = "Товары"
		ordering = ['name', 'type_good']

ddn/apps/core/views.py
from django.views.generic import ListView, DetailView

from .models import Types, Goods
from .mixins import DataMixin


class HomePage(DataMixin, ListView):
	model = Goods
	template_name = "core/main.html"
	context_object_name = 'goods'

	def get_context_data(self, *, object_list=None, **kwargs):
		context = super().get_context_data(**kwargs)
		type_good = self.get_user_context()
		return dict(list(context.items()) + list(type_good.items()))

	def get_queryset(self):
		return Goods.objects.filter(published=True)\
			.select_related('type_good')


class TypesPage(DataMixin, ListView):
	model = Goods
	template_name = 'core/main.html'
	context_object_name = 'goods'
	# 404
	allow_empty = False

	def get_queryset(self):
		return Goods.objects.filter(
			type_good__slug=self.kwargs['type_slug'],
			published=True).select_related('type_good')

	def get_context_data(self, *, object_list=None, **kwargs):
		context = super().get_context_data(**kwargs)
		t = Types.objects.get(slug=self.kwargs['type_slug'])
		t_def = self.get_user_context(type_selected=t.pk)
		return dict(list(context.items()) + list(t_def.items()))


class GoodsPage(DataMixin, DetailView):
	model = Goods
	template_name = 'core/good.html'
	slug_url_kwarg = 'good_slug'
	context_object_name = 'good'

	def get_context_data(self, *, object_list=None, **kwargs):
		context = super().get_context_data(**kwargs)
		good_def = self.get_user_context()
		return dict(list(context.items()) + list(good_def.items()))

ddn/apps/core/templates/core/base.html
{% load static %}
{% load core_tags %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock %} | DDN</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="content">
<div class="block-1">
	<div><h1>Список продуктов</h1></div>
	<div></div>
	<div>
		<ul>
			{% if types == 0 %}
			<li class="selected">Все категории</li>
			{% else %}
			<li><a href="{% url 'core:home' %}">Все категории</a></li>
			{% endif %}
			{% for t in types %}
				{% if t.name__count > 0 %}
					{% if t.pk == types %}
						<li>{{ t.name }}</li>
					{% else %}
						<li><a href="{{ t.get_absolute_url }}">{{ t.name }}</a></li>
					{% endif %}
				{% endif %}
			{% endfor %}
		</ul>
	</div>
</div>
<div class="block-2">
	<div>
		<div>
			{% block breadcrumbs %}{% endblock %}
			<div>
				{% block content %}
				{% endblock %}
			</div>
		</div>
	</div>
</div>
</div>
<div class="content-2">
	{% if page_obj.has_other_pages %}
		<nav class="list-pages">
			<ul class="pagination">
				<!-- Кнопка назад -->
				{% if page_obj.has_previous %}
				<li class="page-num">
					<a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
				</li>
				{% endif %}

				{% for p in paginator.page_range %}
				{% if page_obj.number == p %}
				<li class="page-num page-num-selected">{{ p }}</li>
				{% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
				<li class="page-num">
					<a href="?page={{ p }}">{{ p }}</a>
				</li>
				{% endif %}
				{% endfor %}

				<!-- Кнопка вперед -->
				{% if page_obj.has_next %}
				<li class="page-num">
					<a href="?page={{ page_obj.next_page_number }}">&gt;</a>
				</li>
				{% endif %}
			</ul>
		</nav>
	{% endif %}
</div>
</body>
</html>

ddn/apps/core/templates/core/good.html
{% extends 'core/base.html' %}
{% block content %}
<h1>{{ good.name }}</h1>
<h3>{{ good.pub_time }}</h3>
<h3>{{ good.price }}</h3>
<h3>{{ good.type_good }}</h3>


{{ good.description|linebreaks }}

{% endblock %}

ddn/apps/core/templates/core/list_types.html
{% for t in types %}
{% if t.pk == type_selected %}
<li class="selected">{{ t.name }}</li>
{% else %}
<li><a href="{{ t.get_absolute_url }}">{{ t.name }}</a></li>
{% endif %}
{% endfor %}

ddn/apps/core/templates/core/main.html
{% extends 'core/base.html' %}

{% block title %}
Home Page
{% endblock %}

{% block content %}
<ul class="list clearfix">
	{% for g in goods %}
	<li class="product-wrapper">
		<a href="{{ g.get_absolute_url }}" class="product">
			<div class="panel">
				<p class="type">Тип товара: {{ g.type_good }}</p>
				<p class="date">Дата: {{ g.pub_update|date:"d-m-Y" }}</p>
			</div>
			<h2>{{ g.name }}</h2>
			<p>{{ g.price }}</p>
			<p>{{ g.description|linebreaks|truncatewords:10 }}</p>
			<div class="clear"></div>
		</a>
	</li>
	{% endfor %}
</ul>
{% endblock %}